In [40]:
import pandas as pd
import numpy as np
from openpyxl import load_workbook

# load our file

In [42]:
df = pd.read_excel('Copy of SiC46x Calculator 1.58_MVNP (For Transim)_.xlsm',header=1)

In [43]:
df.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,Lists,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,Mode,UltraSonic,Inductor selection,Part number,NaN,Ceramic Percent

In [44]:

# from tkinter import *
# window=Tk()

# class MyWindow():


#     def __init__(self, win):
#         self.lbl10=Label(win, text="User Input").pack()
#         self.lbl1=Label(win, text='Vin(nom)')
#         self.lbl2=Label(win, text='Vin(Min)')
#         self.lbl3=Label(win, text='Vin(Max)')
#         self.lbl4=Label(win, text='Vout')
#         self.lbl5=Label(win, text='Fsw')
        
#         self.lbl6=Label(win, text='I load')
#         self.lbl7=Label(win, text='Tss')
#         self.lbl8=Label(win, text='I_limit')
#         self.lbl9=Label(win, text='IL Ripple')
#         self.lbl10=Label(win, text='MinVinStartup')
        
        
        
#         self.lbl11=Label(win, text='Mode selection')
#         self.lbl12=Label(win, text='Cout Cer %')
#         self.lbl13=Label(win, text='Cout Ceramic')
#         self.lbl14=Label(win, text='Cout Bulk')
#         self.lbl15=Label(win, text='UltraSonic')
#         self.lbl16=Label(win, text='Inductor Type')
        
        
        
        
#         self.lbl111=Label(win, text='Result')
        
        
        
#         self.t1=Entry()
#         self.t2=Entry()
#         self.t3=Entry()
#         self.t4=Entry()
#         self.t5=Entry()
        
#         self.t6=Entry(master=None)
#         self.t7=Entry()
#         self.t8=Entry()
#         self.t9=Entry()
#         self.t10=Entry()
        
#         self.t11=Entry()
#         self.t12=Entry()
#         self.t13=Entry()
#         self.t14=Entry()
#         self.t15=Entry()
#         self.t16=Entry()
        
#         self.t111=Entry()

    
#         self.btn1 = Button(win, text='Add')
#         self.btn2=Button(win, text='Subtract')
#         self.lbl1.place(x=50, y=50)
#         self.t1.place(x=100, y=50)
#         self.lbl2.place(x=50, y=100)
#         self.t2.place(x=100, y=100)
#         self.lbl3.place(x=50, y=150)
#         self.t3.place(x=100, y=150)
#         self.lbl4.place(x=50, y=200)
#         self.t4.place(x=100, y=200)
#         self.lbl5.place(x=50, y=250)
#         self.t5.place(x=100, y=250)
        
#         self.lbl6.place(x=250, y=50)
#         self.t6.place(x=300, y=50)
#         self.lbl7.place(x=250, y=100)
#         self.t7.place(x=300, y=100)
#         self.lbl8.place(x=250, y=150)
#         self.t8.place(x=300, y=150)
#         self.lbl9.place(x=250, y=200)
#         self.t9.place(x=300, y=200)
#         self.lbl10.place(x=220, y=250)
#         self.t10.place(x=300, y=250)
        
       
#         self.lbl11.place(x=450, y=50)
#         self.lbl12.place(x=450, y=100)
#         self.lbl13.place(x=450, y=150)
#         self.lbl14.place(x=450, y=200)
#         self.lbl15.place(x=450, y=250)
  
  
  
        
        
        
#         self.b1=Button(win, text='Add', command=self.add)
#         self.b2=Button(win, text='Subtract')
#         self.b2.bind('<Button-1>', self.sub)
#         self.b1.place(x=100, y=300)
#         self.b2.place(x=200, y=300)
#         self.lbl111.place(x=100, y=350)
#         self.t111.place(x=200, y=350)

#         #self.spinbox = Spinbox( width=5,  from_=1, to=4)  
#         #self.spinbox.pack(side='right',anchor=N, padx=400,pady=30)
#        # self.spinbox1 = Spinbox( width=5,  from_=1, to=4)  
#         #self.spinbox1.pack(side='right',anchor=N, padx=400,pady=80)

    
#     def add(self):
#         self.t3.delete(0, 'end')
#         num1=int(self.t1.get())
#         num2=int(self.t2.get())
#         result=num1+num2
#         self.t3.insert(END, str(result))
#     def sub(self, event):
#         self.t3.delete(0, 'end')
#         num1=int(self.t1.get())
#         num2=int(self.t2.get())
#         result=num1-num2
#         self.t3.insert(END, str(result))
  
        

 
# w1 = Spinbox(window,width = 5 ,from_=1, to=4)
# w1=w1.place(x=550,y=50)
# w2 = Spinbox(window, width = 5,from_=1, to=100)
# w2=w2.place(x=550,y=100)  


# listbox0 = Listbox(window, width=8, height=2)
# listbox0.place(x=550,y=250)
# mylist0 = ["Enable" ,"Disable" ]
# for Choice in mylist0:
#     listbox0.insert('end', Choice)  




# listbox1 = Listbox(window, width=8, height=2)
# listbox1.place(x=550,y=200) 
# mylist = ['A', 'B', 'C', 'D', 'E','F','G','H','I']
# # load the listbox
# for letter in mylist:
#     listbox1.insert('end', letter)

    
# def on_click_listbox2(event):
#     # get selected line index
#     index = listbox2.curselection()
#     # get the line's text
#     seltext = listbox2.get(index)
#     # show slected text in label
#     label2.configure(text=seltext)

# listbox2 =Listbox(window, width=8, height=2)
# listbox2.place(x=550,y=150) 
# mylist2 = ['AA', 'BB', 'CC', 'DD', 'EE']
# # load the listbox
# for letter1 in mylist2:
#     listbox2.insert('end', letter1) 
# label2 = Label(window, text='SELECT', width=20)
# label2.place(x=600,y=150)
# # use left mouse click on a list item to display selection
# listbox2.bind('<ButtonRelease-1>', on_click_listbox2)    
    
    
    
    
    
# def on_click_listbox1(event):
#     # get selected line index
#     index = listbox1.curselection()
#     # get the line's text
#     seltext = listbox1.get(index)
#     # show slected text in label
#     label1.configure(text=seltext)

# listbox1 = Listbox(window, width=15, height=2)
# listbox1.place(x=550,y=200) 
# mylist = ['33uF / 5mOhm',
# '33uF / 10mOhm',
# '33uF / 15mOhm',
# '33uF / 20mOhm',
# '33uF / 25mOhm',
# '33uF / 30mOhm',
# '33uF / 35mOhm',
# '33uF / 40mOhm',
# '33uF / 45mOhm',
# '33uF / 50mOhm',
# '33uF / 55mOhm',
# '33uF / 60mOhm',
# '33uF / 65mOhm',
# '33uF / 70mOhm',
# '33uF / 75mOhm',
# '33uF / 80mOhm',
# ' 33uF / 85mOhm',
# '33uF / 90mOhm',
# '33uF / 95mOhm',
# '33uF / 100mOhm',
# '47uF / 5mOhm',
# '47uF / 10mOhm',
# '47uF / 15mOhm',
# '47uF / 20mOhm',
# '47uF / 25mOhm',
# '47uF / 30mOhm',
# '47uF / 35mOhm',
# '47uF / 40mOhm',
# '47uF / 45mOhm',
# '47uF / 50mOhm',
# '47uF / 55mOhm',
# '47uF / 60mOhm' ,     
# ' 47uF / 65mOhm',
# '47uF / 70mOhm',
# '47uF / 75mOhm',
# '47uF / 80mOhm',
# '68uF / 75mOhm',
# '68uF / 80mOhm',
# '68uF / 85mOhm',
# '68uF / 90mOhm',
# '68uF / 95mOhm',
# '68uF / 100mOhm',
# '100uF / 5mOhm',
# '100uF / 10mOhm',
# '100uF / 15mOhm',
# '100uF / 20mOhm',
# '100uF / 25mOhm',
# '100uF / 30mOhm',
# '100uF / 35mOhm',
# '100uF / 40mOhm',
# '100uF / 45mOhm',
# '100uF / 50mOhm',
# '100uF / 55mOhm',
# '100uF / 60mOhm',
# '100uF / 65mOhm',
# '100uF / 70mOhm',
# '100uF / 75mOhm',
# '100uF / 80mOhm',
# '100uF / 85mOhm',
# '100uF / 90mOhm',
# '100uF / 95mOhm',
# '100uF / 100mOhm',
# '150uF / 5mOhm',
# '150uF / 10mOhm',
# '150uF / 15mOhm',
# '150uF / 20mOhm'
# '150uF / 25mOhm ',
# '150uF / 30mOhm',
# '150uF / 35mOhm',
# '150uF / 40mOhm',
# '150uF / 45mOhm',
# '150uF / 50mOhm',
# '150uF / 55mOhm',
# '150uF / 60mOhm',
# '150uF / 65mOhm',
# '150uF / 70mOhm',
# '150uF / 75mOhm',
# '150uF / 80mOhm',
# '150uF / 85mOhm',
# '150uF / 90mOhm',
# '150uF / 95mOhm',
# '150uF / 100mOhm',
# '220uF / 5mOhm',
# '220uF / 10mOhm',
# '220uF / 15mOhm',
# '220uF / 20mOhm',
# '220uF / 25mOhm',
# '220uF / 30mOhm',
# '220uF / 35mOhm',
# '220uF / 40mOhm',
# '220uF / 45mOhm',
# '220uF / 50mOhm',
# '220uF / 55mOhm',
# '220uF / 60mOhm',
# '220uF / 65mOhm',
# '220uF / 70mOhm',
# '220uF / 75mOhm',
# '220uF / 80mOhm',
# '220uF / 85mOhm',
# '220uF / 90mOhm',
# '220uF / 95mOhm',
# '220uF / 100mOhm',
# '330uF / 5mOhm',
# '330uF / 10mOhm',
# '330uF / 15mOhm',
# '330uF / 20mOhm',
# '330uF / 25mOhm',
# '330uF / 30mOhm',
# '330uF / 35mOhm',
# '330uF / 40mOhm',
# '330uF / 45mOhm',
# '330uF / 50mOhm',
# '330uF / 55mOhm',
# '330uF / 60mOhm',
# '330uF / 65mOhm',
# '330uF / 70mOhm',
# '330uF / 75mOhm',
# '330uF / 80mOhm' ,
# ' 330uF / 85mOhm',
# '330uF / 90mOhm',
# '330uF / 95mOhm',
# '330uF / 100mOhm',
# '470uF / 5mOhm',
# '470uF / 10mOhm',
# '470uF / 15mOhm',
# '470uF / 20mOhm',
# '470uF / 25mOhm',
# '470uF / 30mOhm',
# '470uF / 35mOhm',
# '470uF / 40mOhm',
# '470uF / 45mOhm',
# '470uF / 50mOhm',
# '470uF / 55mOhm',
# '470uF / 60mOhm',
# '470uF / 65mOhm',
# '470uF / 70mOhm',
# '470uF / 75mOhm',
# '470uF / 80mOhm',
# '470uF / 85mOhm',
# '470uF / 90mOhm',
# '470uF / 95mOhm',
# '470uF / 100mOhm',
# '680uF / 5mOhm',
# '680uF / 10mOhm',
# '680uF / 15mOhm',
# '680uF / 20mOhm',
# '680uF / 25mOhm',
# '680uF / 30mOhm',
# '680uF / 35mOhm',
# '680uF / 40mOhm',
# '680uF / 45mOhm',
# '680uF / 50mOhm',
# '680uF / 55mOhm',
# '680uF / 60mOhm',
# '680uF / 65mOhm ', 
# '680uF / 70mOhm',
# '680uF / 75mOhm',
# '680uF / 80mOhm',
# '680uF / 85mOhm',
# '680uF / 90mOhm',
# '680uF / 95mOhm',
# '680uF / 100mOhm',
# '1000uF / 5mOhm',
# '1000uF / 10mOhm',
# '1000uF / 15mOhm',
# '1000uF / 20mOhm',
# '1000uF / 25mOhm',
# '1000uF / 30mOhm',
# '1000uF / 35mOhm',
# '1000uF / 40mOhm',
# '1000uF / 45mOhm',
# '1000uF / 50mOhm',
# '1000uF / 55mOhm',
# '1000uF / 60mOhm',
# '1000uF / 65mOhm',
# '1000uF / 70mOhm',
# '1000uF / 75mOhm',
# '1000uF / 80mOhm',
# '1000uF / 85mOhm',
# '1000uF / 90mOhm',
# '1000uF / 95mOhm',
# '1000uF / 100mOhm'
#               ]
# # load the listbox
# for letter in mylist:
#     listbox1.insert('end', letter) 
# label1 = Label(window, text='SELECT', width=20)
# label1.place(x=650,y=200)
# # use left mouse click on a list item to display selection
# listbox1.bind('<ButtonRelease>', on_click_listbox1)  
    
    
   



# #lStrand1Spin1.pack(side='right',anchor=N, padx=300,pady=50)
# #lStrand1Spin2 = createSpinbox() #Spinbox 2
# #lStrand1Spin2.grid(row=3, column=1)
# #lStrand1Spin3 = createSpinbox() #Spinbox 3
# #lStrand1Spin3.grid(row=4, column=1)




# MyWindow(window)



# window.title('SiC46xmicroBUCK Family External Component Selection Calculator')
# window.geometry("1000x1000+10+10")
# window.mainloop()

In [45]:
xls = pd.ExcelFile('Copy of SiC46x Calculator 1.58_MVNP (For Transim)_.xlsm')
xls.sheet_names

['Lists', 'GainPhase', 'Capacitors', 'Inductor', 'Calculator']

In [46]:
df=pd.read_excel('Copy of SiC46x Calculator 1.58_MVNP (For Transim)_.xlsm',header=1,sheet_name='GainPhase')

In [47]:
df.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43
0,NaN,NaN,NaN,Gain,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [48]:
df=df.iloc[55:,30:36]

In [49]:
df.head()

,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35
55,F Hz,20logAmp,Find Zero Gain,F Hz,(shiftup phase+ 180),Find Zero Phase
56,1,101.016,101.016,1,165.901,165.901
57,1.01391,101.011,101.011,1.01391,165.709,165.709
58,1.02802,101.006,101.006,1.02802,165.514,165.514
59,1.04232,101.001,101.001,1.04232,165.317,165.317

In [50]:
df=df.rename(columns={"Unnamed: 30": "F Hz", "Unnamed: 31": "20logAmp","Unnamed: 32": "Find Zero Gain", "Unnamed: 33": "F Hz_2", "Unnamed: 34": "shiftup phase+ 180","Unnamed: 35": "Find Zero Phase"})
#df1 = pd.DataFrame(df, columns=['F Hz','20logAmp','Find Zero Gain','(shiftup phase+ 180)','Find Zero Phase'])

In [51]:
df = df.reset_index()

In [52]:
df=df.drop('index',1)
df.head()

,F Hz,20logAmp,Find Zero Gain,F Hz_2,shiftup phase+ 180,Find Zero Phase
0,F Hz,20logAmp,Find Zero Gain,F Hz,(shiftup phase+ 180),Find Zero Phase
1,1,101.016,101.016,1,165.901,165.901
2,1.01391,101.011,101.011,1.01391,165.709,165.709
3,1.02802,101.006,101.006,1.02802,165.514,165.514
4,1.04232,101.001,101.001,1.04232,165.317,165.317

In [53]:
df=df.drop('F Hz_2',1)

In [54]:
df.tail(5)

        F Hz 20logAmp Find Zero Gain shiftup phase+ 180 Find Zero Phase
997   946237 -37.5904       -37.5904              29.04           29.04
998   959401 -37.8154       -37.8154            28.9746         28.9746
999   972747 -38.0405       -38.0405            28.9137         28.9137
1000  986279 -38.2657       -38.2657            28.8575         28.8575
1001   1e+06  -38.491        -38.491            28.8059         28.8059

In [55]:
df.iloc[763,:]

F Hz                     37325
20logAmp              0.589445
Find Zero Gain        0.589445
shiftup phase+ 180     93.7158
Find Zero Phase        93.7158
Name: 763, dtype: object

In [56]:
def Find_CrossOverFreq(num):
    CrossOverFreq=[]
    Array_CrossOver=df[['F Hz','20logAmp','Find Zero Gain']]  #The Array for CrossOver freq Compute index fun
    select_indices = list(np.where(df["Find Zero Gain"] ==num)[0])
    for i in range(len(select_indices)):
        CrossOverFreq.append(Array_CrossOver['F Hz'].iloc[select_indices[i]])
        
    return CrossOverFreq

In [57]:
def Find_PhaseMargin(num):
    PhaseMargin=[]
    Array_CrossOver=df[['F Hz','20logAmp','Find Zero Gain']]  #The Array for CrossOver freq Compute index fun
    select_indices = list(np.where(df["Find Zero Gain"] ==num)[0])
    for i in range(len(select_indices)):
        PhaseMargin.append(df['Find Zero Phase'].iloc[select_indices[i]])
        
    return PhaseMargin

# Here I traied Zero value to find CrossOverFreq as input 0

In [58]:
num=input("Enter the num you want to compute its CrossOver freq= ")

Enter the num you want to compute its CrossOver freq= 0

In [59]:
Find_CrossOverFreq(float(num))

[37844.25847171167,
 38370.72454923025,
 38904.51449943047,
 39445.73020753029,
 39994.47497611223,
 40550.8535448409,
 41114.97211045478,
 41686.938347036135,
 42266.86142656293]

In [60]:
Find_PhaseMargin(float(num))

[93.490600778541,
 93.26525951305753,
 93.03978246471397,
 92.81415890145938,
 92.58837722344862,
 92.36242499033841,
 92.13628894830569,
 91.90995505677716,
 91.68340851486113]

# Compute suggested exact value for inductor  L

In [61]:
#L =(Vin_Max-Vout)/(IL_Ripple/100*Iload)*Vout/Vin_Max*(1/(Fsw*1000))*1000000
#Vin=28.00
#Vin Min=23.00
#Vin Max=32.00
# Vout=12.00
# Fsw=400.00
# Iload=2.00
# Tss=6.0
# I_limit=4.00
# IL Ripple=50
# Min Vin startup=4.50

 $$L=(Vin_Max-Vout)/(IL_Ripple/100*Iload)*Vout/Vin_Max*(1/(Fsw*1000))*1000000 $$

In [62]:
Vin_Max=input("Enter Vin_Max Value = ")
Vout=input("Enter Vout Value = ")
IL_Ripple=input("Enter IL_Ripple Value = ")
Iload=input("Enter Iload Value = ")
Fsw=input("Enter Fsw Value = ")

Enter Vin_Max Value = 32
Enter Vout Value = 12
Enter IL_Ripple Value = 50
Enter Iload Value = 2
Enter Fsw Value = 400

In [63]:
numer=(int(Vin_Max)-int(Vout))*(int(Vout)*1000)*100
den=(int(IL_Ripple)*int(Iload)*int(Vin_Max)*int(Fsw))
L =numer/den
print(L ,"UH")

18.75 UH

# Here I will Compute L value as a simple exampe in GUI

In [64]:

from tkinter import *
window=Tk()

class MyWindow():

    def __init__(self, win):
        self.lbl10=Label(win, text="# Compute the exact value for inductorL").pack()
        self.lbl1=Label(win, text='Vin_Max')
        self.lbl2=Label(win, text='Vout')
        self.lbl3=Label(win, text=' IL_Ripple')
        self.lbl4=Label(win, text='Fsw')
        self.lbl5=Label(win, text='I load')  

        
        self.t1=Entry()
        self.t2=Entry()
        self.t3=Entry()
        self.t4=Entry()
        self.t5=Entry()
        
        self.t10=Entry()
        
        self.t111=Entry()
    
        self.lbl1.place(x=50, y=50)
        self.t1.place(x=120, y=50)
        self.lbl2.place(x=50, y=100)
        self.t2.place(x=120, y=100)
        self.lbl3.place(x=50, y=150)
        self.t3.place(x=120, y=150)
        self.lbl4.place(x=50, y=200)
        self.t4.place(x=120, y=200)
        self.lbl5.place(x=50, y=250)
        self.t5.place(x=120, y=250)
        
        
        self.b1=Button(win, text='Result(LValue)', command=self.L_Calculate)
        self.b1.place(x=100, y=300)
        self.t111.place(x=200, y=305)
    
        
    def L_Calculate(self):
        self.t111.delete(0, 'end')
        result=self.numer()/self.den()
        self.t111.insert(END, str(result)+"  UH")
        
    def numer (self):
       # numer=(int(Vin_Max)-int(Vout))*(int(Vout)*1000)*100
        self.t111.delete(0, 'end')
        num1=int(self.t1.get())
        num2=int(self.t2.get())
        result1=(num1-num2)*(num2*100000)
        return result1
  
    def den(self):
        #den=(int(IL_Ripple)*int(Iload)*int(Vin_Max)*int(Fsw))
        self.t111.delete(0, 'end')
        num1=int(self.t3.get())
        num2=int(self.t5.get())
        num3=int(self.t1.get())
        num4=int(self.t4.get())
        result2=num1*num2*num3*num4
        return result2


        

MyWindow(window)



window.title('SiC46xmicroBUCK Family External Component Selection Calculator')
window.geometry("500x1000+10+10")
window.mainloop()